#pragma once

#define SECURE_CALL_CALLBACKS_MASK 0xfedc

#define SECURE_CALL_RETURN_PUBKEY ((SECURE_CALL_CALLBACKS_MASK << 16) | 0x1)
#define SECURE_CALL_ECDH_COMPUTE ((SECURE_CALL_CALLBACKS_MASK << 16) | 0x2)
#define DEBUG 1