#pragma once

#define SECURE_CALL_CALLBACKS_MASK 0xfedc

#define RETURN_PUBKEY ((SECURE_CALL_CALLBACKS_MASK << 16) | 0x1)
#define ECDH_COMPUTE ((SECURE_CALL_CALLBACKS_MASK << 16) | 0x2)
#define ENCRYPT_MESSAGE ((SECURE_CALL_CALLBACKS_MASK << 16) | 0x3)
#define DECRYPT_MESSAGE ((SECURE_CALL_CALLBACKS_MASK << 16) | 0x4)
#define DEBUG 1